ALTER TABLE shop ADD COLUMN website VARCHAR(100);
ALTER TABLE shop ADD CONSTRAINT unique_phone UNIQUE (phone);
ALTER TABLE supplier ADD COLUMN rating NUMERIC(3, 2) DEFAULT 5.0;
ALTER TABLE car ADD COLUMN year INTEGER CHECK (year >= 1886);
ALTER TABLE customer ADD COLUMN loyalty_points INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN total_price NUMERIC(10, 2);

ALTER TABLE shop ALTER COLUMN address TYPE TEXT USING address::TEXT;
ALTER TABLE supplier ALTER COLUMN contact_info TYPE TEXT USING contact_info::TEXT;
ALTER TABLE car ALTER COLUMN price TYPE NUMERIC(12, 2) USING price::NUMERIC(12, 2);
ALTER TABLE customer ALTER COLUMN phone TYPE VARCHAR(15) USING phone::VARCHAR(15);
ALTER TABLE orders ALTER COLUMN order_date TYPE DATE USING order_date::DATE;

ALTER TABLE shop DROP COLUMN website;
ALTER TABLE shop DROP CONSTRAINT unique_phone;
ALTER TABLE supplier DROP COLUMN rating;
ALTER TABLE car DROP COLUMN year;
ALTER TABLE customer DROP COLUMN loyalty_points;
ALTER TABLE orders DROP COLUMN total_price;
ALTER TABLE shop ALTER COLUMN address TYPE VARCHAR(100) USING address::VARCHAR(100);
ALTER TABLE supplier ALTER COLUMN contact_info TYPE VARCHAR(100) USING contact_info::VARCHAR(100);
ALTER TABLE car ALTER COLUMN price TYPE NUMERIC(10, 2) USING price::NUMERIC(10, 2);
ALTER TABLE customer ALTER COLUMN phone TYPE VARCHAR(20) USING phone::VARCHAR(20);
ALTER TABLE orders ALTER COLUMN order_date TYPE TIMESTAMP USING order_date::TIMESTAMP;